//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DCSEntities : DbContext
    {
        public DCSEntities()
            : base("name=DCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ETOPlaybook> ETOPlaybooks { get; set; }
        public virtual DbSet<ProjectMilestone> ProjectMilestones { get; set; }
        public virtual DbSet<ProjectOwner> ProjectOwners { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectSchedule> ProjectSchedules { get; set; }
        public virtual DbSet<ProjectTracking> ProjectTrackings { get; set; }
        public virtual DbSet<RiskMilestone> RiskMilestones { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<ProjectMultiEmail> ProjectMultiEmails { get; set; }
        public virtual DbSet<TimestampDetail> TimestampDetails { get; set; }
    
        public virtual ObjectResult<GetAllProjects_Result> GetAllProjects()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProjects_Result>("GetAllProjects");
        }
    
        public virtual ObjectResult<GetProjectById_Result> GetProjectById(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectById_Result>("GetProjectById", projectIdParameter);
        }
    
        public virtual ObjectResult<GetProjectById1_Result> GetProjectById1(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectById1_Result>("GetProjectById1", projectIdParameter);
        }
    
        public virtual ObjectResult<GetProjectById2_Result> GetProjectById2(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectById2_Result>("GetProjectById2", projectIdParameter);
        }
    
        public virtual ObjectResult<GetProjectById3_Result> GetProjectById3(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectById3_Result>("GetProjectById3", projectIdParameter);
        }
    
        public virtual ObjectResult<GetProjectById4_Result> GetProjectById4(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectById4_Result>("GetProjectById4", projectIdParameter);
        }
    
        public virtual ObjectResult<GetProjectDetailById_Result> GetProjectDetailById(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectDetailById_Result>("GetProjectDetailById", projectIdParameter);
        }
    
        public virtual ObjectResult<GetDetailForProject_Result> GetDetailForProject(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailForProject_Result>("GetDetailForProject", projectIdParameter);
        }
    
        public virtual ObjectResult<GetDetailForProject1_Result> GetDetailForProject1(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailForProject1_Result>("GetDetailForProject1", projectIdParameter);
        }
    
        public virtual ObjectResult<GetProjectById5_Result> GetProjectById5(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectById5_Result>("GetProjectById5", projectIdParameter);
        }
    
        public virtual ObjectResult<GetProjectDetailById1_Result> GetProjectDetailById1(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectDetailById1_Result>("GetProjectDetailById1", projectIdParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectSchedules_Result> usp_GetProjectSchedules()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectSchedules_Result>("usp_GetProjectSchedules");
        }
    
        public virtual ObjectResult<GetAllProjectsIndex_Result> GetAllProjectsIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProjectsIndex_Result>("GetAllProjectsIndex");
        }
    
        public virtual ObjectResult<usp_GetProjectMultiEmail_Result> usp_GetProjectMultiEmail(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectMultiEmail_Result>("usp_GetProjectMultiEmail", projectIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_RemoveMultiEmail(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_RemoveMultiEmail", iDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_SaveProjectMultiEmail(Nullable<int> iD, Nullable<int> projectId, string email)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_SaveProjectMultiEmail", iDParameter, projectIdParameter, emailParameter);
        }
    
        public virtual ObjectResult<usp_RemoveMultiEmail1_Result1> usp_RemoveMultiEmail1(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RemoveMultiEmail1_Result1>("usp_RemoveMultiEmail1", iDParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectMultiEmail_Result1> usp_GetProjectMultiEmail1(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectMultiEmail_Result1>("usp_GetProjectMultiEmail1", projectIdParameter);
        }
    
        public virtual int usp_GetProjectSummaryDetails(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetProjectSummaryDetails", projectIdParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectSummaryDetails1_Result> usp_GetProjectSummaryDetails1(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectSummaryDetails1_Result>("usp_GetProjectSummaryDetails1", projectIdParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectSummaryDetails1_Result> usp_GetProjectSummaryDetails2(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectSummaryDetails1_Result>("usp_GetProjectSummaryDetails2", projectIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_GetProjectPercentageCompleteByProjectId(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_GetProjectPercentageCompleteByProjectId", projectIdParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectPercentageCompleteByProjectId1_Result> usp_GetProjectPercentageCompleteByProjectId1(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectPercentageCompleteByProjectId1_Result>("usp_GetProjectPercentageCompleteByProjectId1", projectIdParameter);
        }
    
        [DbFunction("DCSEntities", "fDelimitedList2Table")]
        public virtual IQueryable<string> fDelimitedList2Table(string pStringList, string pDelimiter)
        {
            var pStringListParameter = pStringList != null ?
                new ObjectParameter("pStringList", pStringList) :
                new ObjectParameter("pStringList", typeof(string));
    
            var pDelimiterParameter = pDelimiter != null ?
                new ObjectParameter("pDelimiter", pDelimiter) :
                new ObjectParameter("pDelimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[DCSEntities].[fDelimitedList2Table](@pStringList, @pDelimiter)", pStringListParameter, pDelimiterParameter);
        }
    
        public virtual ObjectResult<usp_GetETOPlayBookMileStones_Result> usp_GetETOPlayBookMileStones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetETOPlayBookMileStones_Result>("usp_GetETOPlayBookMileStones");
        }
    
        public virtual ObjectResult<usp_GetProjectMileStones_Result> usp_GetProjectMileStones(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectMileStones_Result>("usp_GetProjectMileStones", projectIdParameter);
        }
    
        public virtual ObjectResult<usp_GetProjectSchedules1_Result> usp_GetProjectSchedules1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProjectSchedules1_Result>("usp_GetProjectSchedules1");
        }
    
        public virtual ObjectResult<string> usp_RemoveOwner(Nullable<int> ownerId)
        {
            var ownerIdParameter = ownerId.HasValue ?
                new ObjectParameter("OwnerId", ownerId) :
                new ObjectParameter("OwnerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_RemoveOwner", ownerIdParameter);
        }
    
        public virtual int usp_RemoveProject(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RemoveProject", projectIdParameter);
        }
    
        public virtual int usp_RemoveProjectMileStone(Nullable<int> mileStoneId, Nullable<int> projectId)
        {
            var mileStoneIdParameter = mileStoneId.HasValue ?
                new ObjectParameter("MileStoneId", mileStoneId) :
                new ObjectParameter("MileStoneId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RemoveProjectMileStone", mileStoneIdParameter, projectIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_SaveProjectMileStone(Nullable<int> mileStoneId, Nullable<int> projectId, string name, Nullable<System.DateTime> startDate, Nullable<decimal> complete, Nullable<int> milestoneStatus)
        {
            var mileStoneIdParameter = mileStoneId.HasValue ?
                new ObjectParameter("MileStoneId", mileStoneId) :
                new ObjectParameter("MileStoneId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var completeParameter = complete.HasValue ?
                new ObjectParameter("Complete", complete) :
                new ObjectParameter("Complete", typeof(decimal));
    
            var milestoneStatusParameter = milestoneStatus.HasValue ?
                new ObjectParameter("MilestoneStatus", milestoneStatus) :
                new ObjectParameter("MilestoneStatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_SaveProjectMileStone", mileStoneIdParameter, projectIdParameter, nameParameter, startDateParameter, completeParameter, milestoneStatusParameter);
        }
    
        public virtual ObjectResult<usp_GetAllProjectsSummary_Result> usp_GetAllProjectsSummary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllProjectsSummary_Result>("usp_GetAllProjectsSummary");
        }
    }
}
