//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectMilestones = new HashSet<ProjectMilestone>();
            this.ProjectSchedules = new HashSet<ProjectSchedule>();
            this.ProjectTrackings = new HashSet<ProjectTracking>();
            this.ProjectStatus = new HashSet<ProjectStatu>();
        }
    
        public int ID { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<bool> EOPlaybook { get; set; }
        public Nullable<int> EOPlaybookId { get; set; }
        public Nullable<bool> PeerReview { get; set; }
        public Nullable<bool> ManagementApproval { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProjectOwnerANTMId { get; set; }
        public Nullable<int> ProjectOwnerExternalId { get; set; }
        public string Description { get; set; }
        public string ExecutiveStatus { get; set; }
        public string Accomplishments { get; set; }
        public string KeyRisksAndIssues { get; set; }
        public string Direction { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string FundingAsk { get; set; }
    
        public virtual ETOPlaybook ETOPlaybook { get; set; }
        public virtual ETOPlaybook ETOPlaybook1 { get; set; }
        public virtual ICollection<ProjectMilestone> ProjectMilestones { get; set; }
        public virtual ProjectOwner ProjectOwner { get; set; }
        public virtual ProjectOwner ProjectOwner1 { get; set; }
        public virtual ICollection<ProjectSchedule> ProjectSchedules { get; set; }
        public virtual ICollection<ProjectTracking> ProjectTrackings { get; set; }
        public virtual ICollection<ProjectStatu> ProjectStatus { get; set; }
    }
}
