//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.ProjectStatus = new HashSet<ProjectStatu>();
            this.ProjectStatus1 = new HashSet<ProjectStatu>();
            this.ProjectStatus2 = new HashSet<ProjectStatu>();
            this.ProjectStatus3 = new HashSet<ProjectStatu>();
            this.ProjectStatus4 = new HashSet<ProjectStatu>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ProjectStatu> ProjectStatus { get; set; }
        public virtual ICollection<ProjectStatu> ProjectStatus1 { get; set; }
        public virtual ICollection<ProjectStatu> ProjectStatus2 { get; set; }
        public virtual ICollection<ProjectStatu> ProjectStatus3 { get; set; }
        public virtual ICollection<ProjectStatu> ProjectStatus4 { get; set; }
    }
}
