//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimestampDetail
    {
        public int ID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ColumnName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
