//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS.DAL
{
    using System;
    
    public partial class usp_GetProjectMultiEmail_Result1
    {
        public int ID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Email { get; set; }
    }
}
